from base import *
import platform,subprocess
def main():
    if (RUN/'frozen_config.json').exists():print('Freeze preserved');return
    config={'run_id':RUN.name,'seed':SEED,'previous_run':PREV.name,'control_lambdas':[0,.25,.5,.9,.99],'control_c':.5,'hub_k':[10,20,50],'tie_policy':'stable original node order; report floating-point rank violations, compare 12-decimal canonical ranks separately without replacing original values','empirical_module_rule':{'discovery':'GSE115513 selected500 suppliedscale','distance':'1-absolute Spearman','linkage':'average','maxclust':8,'minimum_discovery_size':10,'minimum_external_nodes':10,'minimum_coverage':.25,'example_rule':'two largest eligible discovery modules, ties ascending moduleID','module_hub_k':5,'significance':'none; descriptive density and within-module connectivity rank agreement'},'simulation':{'p':120,'modules':4,'module_size':30,'n':[60,240],'loading_scale':[.5,1.0],'nuisance_amplitude':[0,.6],'null_n':[60,240],'planned_datasets_per_cell':60,'bootstrap_attempts':100,'pilot_datasets':2,'runtime_budget_seconds':2700,'precision_goal':'worst-case normal half-width <=.13 for [0,1] dataset-mean endpoints at R60; actual MCSE also reported','latent_loadings':'each module linearly spaced .35 to .85 times scale','independent_noise_sd':1,'nuisance_loadings':'amplitude times linspace(.2,1.2,120) reversed within alternate modules','hubs':'three largest loading nodes per module =12; verify population nuisance-free association ordering','module_algorithm':'normalized spectral clustering known K4, precomputed hard/soft adjacency, assign_labels cluster_qr, fixed seed; algorithmic disconnected-graph warnings logged','hard':'abs Spearman >= full-pair .975 quantile','soft':'abs Spearman^6','common_support':'soft weight restricted to same sample reference hard edges; CV descriptive only','independent_reproducibility':'two independently generated samples per dataset, same n; both reconstructed with same settings','null_truth':'no planted signal; latent hub and module recovery undefined; report apparent stability and independent reproducibility'},'additional_cohort':{'max_new_candidates':5,'search_budget_minutes':25,'max_compressed_download_mb':500,'min_carcinoma_arrays':30,'min_unique_mapped_nodes':100,'eligibility':'primary colorectal carcinoma tissue miRNA; untreated preferred; metadata and processed expression inspectable','selection_order':'metadata specimen/condition similarity; explicit persons; larger n; ascending accession; no network outcomes'},'annotation':'targeted primary-source interpretation of predeclared largest modules only; no enrichment unless independent accessible target coverage and bias-aware null feasible','local_total_budget_hours':3,'no_nested_EBC_population_run':True,'no_new_model_tuning':True}
    write_json(RUN/'frozen_config.json',config)
    txt('analysis_amendment.md','''# Analysis amendment — 2026-09-07

This bounded study follows knowledge of both earlier empirical runs and GSE41655 outcomes. It is not prospective preregistration of the whole study. The frozen configuration records all new comparative settings before their calculation. The question is when low conditional CV corresponds to accurate or externally reproducible hub/module identification, not whether a preferred method wins.

New tests: (1) constant background affine control on full fixed universes, c=.5 and lambda0,.25,.5,.9,.99, ranks checked including numerical ties; (2) hub k10,20,50 selection/rank variability on original1000 draws; (3) expression-factor simulation with120 variables,4 modules, two n, two signal strengths, nuisance contrast and nulls; (4) fixed discovery-only8 average-linkage modules, all modules reported and eligibility size/coverage frozen; (5) one additional metadata-selected public primary colorectal tissue cohort screened without outcome selection; (6) constant .5 and train-bootstrap-only intercept prediction baselines on existing20 splits; (7) paired graph/hub/module consequences.

Simulation pilots are for runtime only: two independent datasets, one weak n60 and one strong+nuisance n240. Do not view comparative pilot metrics before production count is frozen. Planned60 datasets per each of10 cells,100 bootstrap attempts, two independent samples per dataset. Budget45 minutes compute; if pilot projects beyond budget use30 per cell and state weaker precision before reading production results. No successful-draw replacement, model tuning or preferred-outcome stopping. Dataset units, bootstrap MC and empirical split dependence stay separate. Fixed-known K is an oracle simplification for simulation module recovery, not estimated biological module count.

Modules use discovery alone (supplied-scale selected500, absolute-Spearman average linkage, maxclust8). A module is eligible for external summaries with discovery size>=10, mapped external size>=10 and coverage>=25%; excluded modules remain listed. Examples are the two largest eligible discovery modules, never highest-preservation modules. Each external cohort has a frozen-discovery-cutoff A and density-matched B on its exact mapped universe. Module connectivity metrics are descriptive, without preservation-significance thresholds. No miRNA target enrichment will be invented from incomplete target/coverage inputs. Public primary-source functional context is separate from independent validation.

The displayed empirical bootstrap graph is replicate0 by rule, using a discovery-only deterministic circular/module layout shared with its reference. Direct graph accounting uses the original primary1000 attempts and their fixed cutoff. Previously failed tissue1000-feature200 attempts are audited from saved pair/constant counts without rerunning them.

Baseline p=.5 must yield binary Brier .25. Train-intercept probability is total train-bootstrap disappearances/total train edge-trials across the original training-eligible reference edges, calculated before and without test eligibility/outcomes. Test scores share each split's saved evaluable edges. Full-universe Brier bounds use unknown labels y in{0,1}, per-edge minimum/maximum squared loss from its fixed trained prediction. Bounds are identification bounds, not probability intervals.

Original raw files and prior outputs remain untouched. Research agents inspect primary literature and official journal policy while local computation proceeds. Overall working budget3 hours; checkpoints and genuinely blocked inputs remain visible. HTML is the required self-contained review artifact, with embedded data figures; PDF optional if readily supported. No publishing, push, contact or paid retrieval.
''')
    inv=[]
    for root,manifest,key in [(OLD,OLD/'output_inventory.json',None),(PREV,PREV/'final_manifest.json','artifact_inventory')]:
        data=json.loads(manifest.read_text());data=data[key] if key else data
        for r in data:
            p=root/r['path'];inv.append({'run':root.name,'path':str(p),'expected_sha256':r['sha256'],'actual_sha256':sha(p),'matches':sha(p)==r['sha256']})
    csv('previous_artifact_inventory',inv);assert all(r['matches'] for r in inv)
    import pymupdf
    manuscript=Path('C:/Users/Samsunh/Downloads/Integrating_ceRNA_Network_Topology_with_Expression_Features_Improves_Pan_Cancer_Detection_in_Liquid_Biopsy.pdf')
    doc=pymupdf.open(manuscript);txt('manifests/manuscript_actual_text.txt','\n'.join(p.get_text() for p in doc));doc[0].get_pixmap(matrix=pymupdf.Matrix(1,1)).save(RUN/'figures/manuscript_title_check.png')
    write_json(RUN/'manifests/start.json',{'utc':time.strftime('%Y-%m-%dT%H:%M:%SZ',time.gmtime()),'commit':git('rev-parse','HEAD'),'branch':git('branch','--show-current'),'git_status':git('status','--short'),'python':sys.version,'platform':platform.platform(),'packages':subprocess.check_output([sys.executable,'-m','pip','freeze'],text=True),'config_sha256':sha(RUN/'frozen_config.json'),'amendment_sha256':sha(RUN/'analysis_amendment.md'),'manuscript_sha256':sha(manuscript),'manuscript_pages':len(doc),'prior_artifacts_verified':len(inv),'prior_source_hashes':{str(p.relative_to(BASE)):sha(p) for folder in ['src','followup_src'] for p in (BASE/folder).glob('*.py')}})
    print('Frozen. Prior hashes:',len(inv),'manuscript first-page title:',doc[0].get_text()[:220])
if __name__=='__main__':main()
